apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: {{ .Values.service.type }}
  selector:
    app: kibana
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}