apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "5Gi" }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
