apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: {{ .Values.service.type }}
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}